alias g='git'
alias gst='git status'
alias gci='git commit'
alias gco='git checkout'
alias gl='git pull'
alias gp='git push'

alias glo='git pull origin'
alias gpo='git push origin'
alias glom='git pull origin master'
alias gpom='git push origin master'
alias gloc='git pull origin $(current_branch)'
alias gpoc='git push origin $(current_branch)'

alias gld='git pull dropbox'
alias gpd='git push dropbox'
alias gldm='git pull dropbox master'
alias gpdm='git push dropbox master'
alias gldc='git pull dropbox $(current_branch)'
alias gpdc='git push dropbox $(current_branch)'

