alias f='cd ~/code/fs'
alias fstech='cd ~/code/github/fstech'
alias fcor='cd ~/code/fs/core'
alias fcrm='cd ~/code/fs/crm'
alias fcom='cd ~/code/fs/crm'
alias fsal='cd ~/code/fs/sales'
alias fsle='cd ~/code/fs/sleipnir'
alias fupl='cd ~/code/fs/uploader'
alias ftag='cd ~/code/fs/tags'
alias fmai='cd ~/code/fs/mailman'
alias ffee='cd ~/code/fs/feeder'
alias fvoi='cd ~/code/fs/voice'
alias fsee='cd ~/code/fs/seeker'
alias fpay='cd ~/code/fs/payments'
alias fint='cd ~/code/fs/integrator'
alias faut='cd ~/code/fs/automator'
alias fsalf='cd ~/code/fs/sales-frontend'
alias fcrmf='cd ~/code/fs/crm-frontend'
alias fappf='cd ~/code/fs/app-frontend'
alias fvoif='cd ~/code/fs/voice-frontend'
alias fsetf='cd ~/code/fs/settings-frontend'
alias fperf='cd ~/code/fs/permissions-frontend'

alias cdp='cd ~/code/private'
alias cds='cd ~/code/spikes'
alias cdg='cd ~/code/github'
alias cdm='cd ~/code/github/mehowte'
alias cdd='cd ~/code/github/mehowte/dotfiles'

alias mvd='cdd && mvim'

setopt auto_cd
cdpath=(~/code/fs ~/code/github/fstech ~/code/private ~/code/spikes)

alias pw='cd ~/code/private/programmingworkout'
alias kp='cd ~/code/private/kanapress'
